### PR TITLE
Frontend redesign

### LINKED ISSUE #142: UI: re-style website
The current design is more than a bit crap, visually, and it's starting to look dated now.

### PR DESCRIPTION
**Pull request by knojector**
In this PR I refactored the Frontend to make it more Bootstrap compliant and gave it a fresh new look using the [Bootswatch Yeti Theme](https://bootswatch.com/3/yeti/). 

Sure, there are still a lot of things that can be improved but for now the old look is gone.

Resolves #142

### CODE REVIEW

**Comment by luispabon** [comment]
:+1: :+1: :+1: :+1:  going to try this right now

**Comment by luispabon** [comment]
This looks really good indeed, thank you very much. Other than what I pointed out about the footer, there's an issue in firefox at 1920x1080 where the extensions selector doesn't scale up horizontally all the way like it does in chrome:

image

**Comment by knojector** [comment]
whops, didn't notice that. Should now be fixed.

**Comment by q2dg** [comment]
:-(

**Comment by leandroruel** [comment]
i think this merge needs be redesigned again, because, you know... it's 2020 and Bootstrap is now v4.4 almost 5 and Bootswatch looks old now. i can PR this if you want.

**Pull request closed without merging**
