### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Dhvanil25**
Improve Docs

### CODE REVIEW

**Comment by tjorim** [comment]
This looks like hacktoberfest spam, tag this PR as invalid.

**Comment by luispabon** [comment]
Thanks for the heads up @tjorim. What's the objective of those spam PRs? This is new to me.

**Comment by alister** [comment]
Hacktoberfest - 4 accepted pull requests to an open source project - and you get a t-shirt. There was a whole stream of similar zero-quality PRs made to a couple of other projects.  Tag them as 'spam' and/or 'invalid' and DigitalOcean will ignore them for the competition.

**Comment by luispabon** [comment]
Thanks for the info :+1:

**Pull request closed without merging**
